#!/bin/sh

git_flow_exists() {
  command -v git-flow >/dev/null 2>&1
}

git_flow_initialized() {
  git config gitflow.branch.develop && git config gitflow.branch.master
}

if git_flow_exists && git_flow_initialized; then
  git branch -d $(git branch --merged | grep -v $(git config gitflow.branch.develop))
else
  echo 'You need to have git-flow installed and initialized to run this command' 1>&2
fi

